---
title: "Lista 04 - dplyr"
author: "Klysman"
date: "21/01/2021"
output: html_document
---

```{r LeituraDados, message=FALSE}

    install.packages('dplyr')
    install.packages("gapminder")
    require(dplyr)
    require(gapminder)
    require(ggplot2)
    require(stringr)

```


```{r InsirirColunaOrdem}

  dados_brasil <- subset(gapminder, country == "Brazil")

  dados_brasil["ordem"] <- c(1:12)

```

```{r InsirirColunaDecada}

  dados_brasil["decada"] <- c("50","50","60","60","70","70", "80","80","90","90","2000","2000")
  #dados_brasil["seculo"] <- c("1900","1900","1900","1900","1900","1900", "1900","1900","1900","1900","2000","2000")

```

```{r InsirirColunaSeculo}

  if ( dados_brasil$year <= 2000) {
    dados_brasil$seculo <- c("1900")
  } else if( dados_brasil$year > 2000 ) {
    dados_brasil$seculo <- c("2000")
  }

```
```{r ArredondarValoresLifeEXP}
  dados_brasil$lifeExp <- round(dados_brasil$lifeExp, 2)

```



```{r ExpectativaMediaBrasil}

  ExpMedia <- mean(dados_brasil$lifeExp)

```



```{r}
  install.packages("gapminder")
  require(gapminder)
  require(dplyr)

  #Quais os três primeiros países com maior população (“pop”) em 1957?
  max_pop_1957 <- gapminder %>%
      filter(year == 1957) %>%
      select(country, pop) %>%
      arrange(desc(pop)) %>%
      head(3)

```



```{r}
  #Crie uma coluna denominada “lifeExpMonths” com a expectativa de vida em meses.

  gapminder["lifeExpMonths"] <- c(gapminder$lifeExp/12)

  #Quais os três primeiros países com a maior expectativa de vida em meses?

 
  max_lifeexp_mes <- gapminder %>%
      select(country, lifeExpMonths) %>%
      arrange(desc(lifeExpMonths)) %>%
      head(3)


```



```{r}
  #Quais os três primeiros países com a maior expectativa de vida em meses entre os anos de 1960 e 1980?
  #require(gapminder)
  #gapminder["lifeExpMonths"] <- c(gapminder$lifeExp/12)
  max_lifeexp_mes_1960_1980 <- gapminder %>%
      filter(year > 1960, year < 1980) %>%
      select(country, lifeExpMonths) %>%
      arrange(desc(lifeExpMonths)) %>%
      head(3)

```



```{r}
  #Qual o menor PIB (gdpPercap) de toda a base de dados?
  menor_gdpPercap <- gapminder %>%
      select(country, gdpPercap) %>%
      arrange(across(gdpPercap)) %>%
      tail(3)
      
      #ggplot() +
      #geom_point(aes(x = country, y = gdpPercap ))

```



```{r}
  #Qual a população total no continente americano em 1962?
  require(gapminder)
  americas_1962 <- gapminder %>%
  filter(year == 1962, continent == "Americas")


  pop_total_americas_1962 <- sum(americas_1962$pop)
  
  

```



```{r}
  #Qual a mediana da expectativa de vida no mundo entre os anos 1980 e 2000?
  require(gapminder)
  media_1980_2000 <- gapminder %>%
  filter(year > 1980, year < 2000)

  median_media_1980_2000 <- median(media_1980_2000$lifeExp)
  
  

```




```{r}
  #Qual o maior valor de PIB no mundo entre os anos de 1980 e 2000?
  require(gapminder)
  media_1980_2000 <- gapminder %>%
  filter(year > 1980, year < 2000)

  max_pip_1980_2000 <- max(media_1980_2000$gdpPercap)
  
  

```




```{r}
  #Qual o maior valor de PIB no mundo entre os anos de 1980 e 2000?
  require(gapminder)
  media_1980_2000 <- gapminder %>%
  filter(year > 1980, year < 2000)

  min_pip_1980_2000 <- min(media_1980_2000$gdpPercap)
  
  

```






```{r}
##CODIGOS =============================================================


   # 2.1. Funcao "filter()"
    
    gap_brasil <- gapminder %>% 
      filter(country == "Brazil")
    
    gap_ame_2007 <- gapminder %>%
      filter(continent == "Americas",
             year == 2007)
    
    # 2.2. Funcao "select()"
    
    gap_ame_2007 <- gapminder %>%
      filter(continent == "Americas",
             year == 2007) %>%
      select(-continent, -year)
    
    # 2.3. Funcao "arrange()"
    
    covid %>%
      filter(location == "Brazil",
             ano == 2020) %>%
      select(date, new_cases, total_cases, total_deaths) %>%
      arrange(desc(new_cases), desc(total_cases)) %>%
      head() %>% 
      ggplot(aes(x = date, y = new_cases)) +
      geom_point()
    
    ## Exemplo ggplot2
    
    covid %>%
      select(location, continent, ano, total_deaths, total_cases) %>%
      filter(ano == 2020) %>%
      select(-ano) %>%
      filter(location != "World") %>%
      filter(continent != "") %>%
      ggplot() +
      geom_boxplot(aes(x = continent, y = total_deaths/total_cases, fill = continent)) +
      scale_y_log10()
    
    # 2.4. Funcao "mutate()"
    
    dados <- covid %>%
      filter(location == "Brazil",
             ano == 2020) %>%
      select(date, total_cases, total_deaths) %>%
      mutate(letal = total_deaths/total_cases,
             total_cases = total_cases/1000,
             let_alta = ifelse(letal >= 0.05, 1, 0))
```














